name: 12 - Working with Outputs

on: 
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
          - superman
        default: success 

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT"
      
      - name: Build
        id: build
        run: echo "status=${{ github.event.inputs.build-status }}" >> "$GITHUB_OUTPUT" 

      - name: Check for Errors
        if: ${{ github.event.inputs.build-status == 'failure' }}
        run: |
          echo "Error: Simulating a build failure"
          exit 1

      - name: check for success
        if: ${{ github.event.inputs.build-status == 'superman'}}
        run: echo "Status is set to superman!"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Deploy
        run: echo "Deploying"
